// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetFactions():Promise<Array<domain.Faction>>;

export function GetUnitByType(arg1:string):Promise<domain.Unit|boolean>;

export function GetUnitsByFaction(arg1:string):Promise<Record<string, Record<string, Array<domain.Unit>>>>;
