// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFactions() {
  return window['go']['main']['App']['GetFactions']();
}

export function GetUnitByType(arg1) {
  return window['go']['main']['App']['GetUnitByType'](arg1);
}

export function GetUnitsByFaction(arg1) {
  return window['go']['main']['App']['GetUnitsByFaction'](arg1);
}
